### ISSUE TITLE
Groups of groups

### ISSUE THREAD

**Issue by jtyr** [spectras/keyleds#30]
It would be nice if we could define groups which contain other groups:

```yaml

groups:
  chars:
    first_row: [q, w, e, r, t, y, u, i, o, p]
    second_row: [a, s, d, f, g, h, j, k, l]
    third_row: [z, x, c, v, b, n, m]

effects:
  keyleds-default:
    plugins:
      - effect: fill
        color: black
        chars: cyan
      - plugin: breathe
        group: first_row
        period: 5000
        color: blue
```

**Comment by spectras** [comment]
You mean, as way to make the file look better, or carrying some feature?
I mean, from your example, how is it functionally different from this?
```yaml
groups:
  # some char groups
  first_row: [q, w, e, r, t, y, u, i, o, p]
  second_row: [a, s, d, f, g, h, j, k, l]
  third_row: [z, x, c, v, b, n, m]
```
