### ISSUE TITLE
Cool Effects repository

### ISSUE THREAD

**Issue by spectras** [spectras/keyleds#8]
*This is not an issue.*
Some day perhaps I (or someone) will offer a repository where to put effects. In the meantime…

Created a cool effect? Post it here!

**Comment by rferro** [comment]
# Pong Plugin

![ezgif-4-4c53044c5e](https://user-images.githubusercontent.com/782398/33974917-4ce1f43c-e072-11e7-94a6-a747803dac4e.gif)

## Sample configuration

```yaml
pongEffect:
  groups:
    group1: [ F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12]
    group2: [
      grave, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, minus, equal, backspace,
      backslash, rbrace, lbrace, p, o, i, u, y, t, r, e, w, q, tab,
      capslock, a, s, d, f, g, h, j, k, l, semicolon, apostrophe, enter,
      rshift, slash, dot, comma, m, n, b, v, c, x, z, lshift,
      lctrl, lmeta, lalt, space, ralt, rmeta, compose, rctrl,
    ]
  plugins:
    - effect: fill
      color: black
    - effect: pong
      group: group1
    - effect: pong
      group: group2
      color: blue
      speedTime: 0.07
      fadeTime: 1
```

## Options

- **`group`**: `default: keyleds.db`
- **`color`**: `default: red`
- **`speedTime`**: `default: 0.1`
- **`fadeTime`**: `default: 0.5`

```lua
-- pong.lua

color = tocolor(keyleds.config.color) or tocolor('red')
transparent = tocolor(color.red, color.green, color.blue, 0)
speedTime = tonumber(keyleds.config.speedTime) or 0.1
fadeTime = tonumber(keyleds.config.fadeTime) or 0.5
keys = keyleds.groups[keyleds.config.group] or keyleds.db

function pong (buffer)
  local i, rev = false

  while true do
    local start, endx, step, i

    if rev then
      start = #keys
      endx = 2
      step = -1
    else
      start = 1
      endx = #keys - 1
      step = 1
    end

    for i = start, endx, step do
      local key = keys[i]

      buffer[key] = fade(fadeTime, color, transparent)
      wait(speedTime)
    end

    rev = not rev
  end
end

buffer = RenderTarget:new()

thread(pong, buffer)

function render(ms, target)
  target:blend(buffer)
end
```

**Comment by spectras** [comment]
Good job, cool effect!
By the way, if you have suggestions to improve the API, feel free to open a ticket, I would be glad to have some feedback from people using it.

**Comment by Suppr** [comment]
# ProgressBar Plugin update via Dbus
![out](https://user-images.githubusercontent.com/9516964/46530684-9fc12c00-c8ab-11e8-8029-73ba8b5c01e4.gif)
## Sample Config

- **delimiter** : default : red
- **progress** : default : green
- **noprogress** : default : transparent
- **group** : default : functions keys

```yaml
    progressbar:
        groups:
            bar: [esc,F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12, sysrq, scrolllock, pause]
        plugins:
            - effect: progress
              delimiter: red 
              progress: green
              noprogress: black
              group: bar
```

## progress.lua

```lua
delimiterColor = tocolor(keyleds.config.delimiter) or tocolor('red')
progressColor= tocolor(keyleds.config.progress) or tocolor('green')
noprogressColor= tocolor(keyleds.config.noprogress) or tocolor(progressColor.red, progressColor.green, progressColor.blue, 0)
progressValue = tonumber(-1)
lineDef = keyleds.groups[keyleds.config.group] or {"F1","F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10", "F11","F12"}

function onGenericEvent(data)
    if data.effect ~= "progress" then return end
    newProgressValue = data.progressValue
    if newProgressValue then 
        progressValue = tonumber(newProgressValue) 
        buffer = RenderTarget:new()
        thread(progressBar, buffer)
    end
end

function progressBar(keyboard)
    print('Value receive from DBUS : ',progressValue)
    if (progressValue > 0 and progressValue <= 1) then
        keyboard[lineDef[1]] = delimiterColor
        keyboard[lineDef[#lineDef]] = delimiterColor
        indice = 1/(#lineDef -2)
        for i=1,#lineDef-2,1 do
            if ((progressValue >= (indice *(i -1))) and (progressValue <= indice * i)) then
                calcvalue = (progressValue - (indice*(i-1))) / ((indice*i)-(indice*(i-1)))
                keyboard[lineDef[i+1]] = progressColor* calcvalue
            elseif progressValue < (indice*i) then
                keyboard[lineDef[i+1]] = noprogressColor
            elseif progressValue > indice * (i-1) then
                keyboard[lineDef[i+1]] = progressColor
            end
        end
    end 
end

buffer = RenderTarget:new()
function render(ms, target)
    target:blend(buffer)
end
```
## Dbus

Testing from terminal :
```bash
dbus-send --print-reply  --session --dest=org.etherdream.KeyledsService /Service org.etherdream.keyleds.Service.sendGenericEvent dict:string:string:"effect","progress","progressValue","0.5"
```
## Example
### Python Mpris progress (Clementine)

```python3
#!/usr/bin/python3
import re
from pydbus import SessionBus
import time

bus = SessionBus()

while True :
    if 'org.etherdream.KeyledsService' in bus.dbus.ListNames():
        keyledsbus = bus.get('org.etherdream.KeyledsService', '/Service')
        dictio = {
            "effect":"progress",
            "progressValue":str(-1)
        }
        if 'org.mpris.MediaPlayer2.clementine' in bus.dbus.ListNames():
            mediabus = bus.get('org.mpris.MediaPlayer2.clementine', '/org/mpris/MediaPlayer2')
            
            progress = mediabus.Position / mediabus.Metadata.get("mpris:length", -1)
            dictio = {
                "effect":"progress",
                "progressValue":str(progress)
            }
        keyledsbus.sendGenericEvent(dictio)
    time.sleep(1)
```
### Powershell Mpris progress (multi-player)

```powershell
$baseopt = 'dbus-send --print-reply --session --dest=org.etherdream.KeyledsService /Service org.etherdream.keyleds.Service.sendGenericEvent dict:string:string:"effect","progress","progressValue","'
$MprisDest = "org.mpris.MediaPlayer2."
$MprisPlayersList = "plasma-browser-integration","mpv","clementine"

while ($true) {
    $dbuslist = dbus-send --session --dest=org.freedesktop.DBus --type=method_call --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames | Select-String -Pattern '"(.*)"' | ForEach-Object {$_.tostring().split('"')[1]}
    if ('org.etherdream.KeyledsService' -in $dbuslist) {
        $outvalue = '-1'
        foreach ($player in $MprisPlayersList) {
            $dest = $MprisDest + $player
            if ($dest -in $dbuslist) {
                $MPosition = (dbus-send --print-reply  --session --dest=$dest /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Position | Select-String -Pattern 'int64').ToString().Split(" ")[-1]
                $MLength = (dbus-send --print-reply  --session --dest=$dest /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Metadata | Select-String -Pattern 'int64').ToString().Split(" ")[-1]
                $MStatus = (dbus-send --print-reply  --session --dest=$dest /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:PlaybackStatus | Select-String -Pattern 'string').ToString().Split('"')[1]
                if ($MStatus -eq "Playing") {
                    if (($null -ne $MPosition) -and ($null -ne $MLength)) {
                        if (($MPosition -match '^\d+$') -and ($MLength -match '^\d+$')) {
                            $outvalue = $MPosition / $MLength
                            break
                        }
                    }
                }
            }
        }
        $outopt = $baseopt + $outvalue + '"'
        Invoke-Expression $outopt | Out-Null
        Start-Sleep -Seconds 0.5
    }
}
```

**Comment by spectras** [comment]
That's great.
I like the use of a group to define the sequence of keys. Actually, order is not guaranteed yet, it just so happens the way it works now does not reorder them. But this shows guaranteeing the order is the right thing to do.

Do you have any feedback about the API? Things that could be improved to make writing such scripts easier?

**Comment by msagerup** [comment]
sorry. but where do i add or find these files ?

**Comment by spectras** [comment]
Hello  @msagerup.
You may find the complete description of the path [here](https://github.com/keyleds/keyleds/wiki/LUA-Introduction#enabling-lua-support), but unless you have an unusual setup, the TL;DR version is:

* `/usr/share/keyledsd/effects/` for effects bundled with keyleds.
* `~/.local/share/keyledsd/effects/` for your own custom effects. You may need to create the directory.

I hope it helps, otherwise please let me know.

**Comment by dingram** [comment]
Here's an effect I created, though I thought the code was too long to past into a comment: https://gist.github.com/dingram/a66ea6c1fc97acaa211409b7b27d0b02

The effect highlights keys in order, with configurable fade durations (even on a per-key basis). This can give the appearance of someone typing at the keyboard with the "feedback" effect active. A simple configuration is:

```
  screenlock:
    groups:
      locked: [l, o, c, k, e, d]
    plugins:
      - effect: fill
        color: black
      - effect: message
        group: locked
        color: 993300
        initialDelay: 1000
        keyTime: 400
        attackPercent: 0
        repeatInterval: 2000
```

which looks like this:

![locked-animation](https://user-images.githubusercontent.com/93105/99060955-b82ac700-2598-11eb-9c89-2bbb17bfe884.gif)

And a more advanced configuration is:

```
  perkeytest:
    plugins:
      - effect: fill
        color: black
      - effect: message
        message: "t:500 e:750 s:1000 t:2000"
        color: ffff00
        repeatInterval: 2000
        attackPercent: 90
        decayPercent: 0
```

which displays "test" with increasing highlight times for each key, like this:

![test-animation](https://user-images.githubusercontent.com/93105/99062808-72bbc900-259b-11eb-9c09-78ca75759a63.gif)

At some point, I may extend this further to support configurable pauses between keys, e.g. `"t :500 e :1000 s :250 t"`.

**Comment by mvrozanti** [comment]
# Snake :snake: 

![snake](https://i.imgur.com/s8jJ5gZ.gif)

---
### snake.lua
https://gist.github.com/mvrozanti/9936aa9b81a450e0f1ec803d115274f4

### Config
```yaml
snakegame:
    groups:
        grid: [esc      , F1 , F2 , F3 , F4 , F5 , F6 , F7 , F8    , F9  , F10       , F11        , F12    ,
               1        , 2  , 3  , 4  , 5  , 6  , 7  , 8  , 9     , 0   , minus     , equal      , backspace,
               tab      , q  , w  , e  , r  , t  , y  , u  , i     , o   , p         , lbrace     , rbrace ,
               capslock , a  , s  , d  , f  , g  , h  , j  , k     , l   , semicolon , apostrophe , enter  ,
               lshift   , z  , x  , c  , v  , b  , n  , m  , comma , dot , slash     , rshift     , rshift]
    plugins:
        - effect: snake
          group: grid
          width: 13
          height: 5
          snakeColor: green
          foodColor: red
          snakeHeadColor: orange
          snakeTailColor: purple
          delay: 100
          onKey: true
```

Grid needs to be a rectangle at the moment

---

Might make a winning version in the future but I like it how this turned out lol awesome library!

**Comment by mvrozanti** [comment]
# Lightning Feedback :zap: 

![lightning](https://i.imgur.com/rRNbTf6.gif)

### lightning.lua
https://gist.github.com/mvrozanti/5c99fd1d51a1b7f3381954021ebc8671



---

### Config
```yaml
- effect: lightning
  numJumps: 15
  numSplits: 1
  delay: 0.05
  startColor: red
  endColor: cyan
  fadeTime: 1

```

Just had to do this one also. The key neighbors are hardcoded, I tried having nested lists in the config as groups but ended up sticking with the neighbor table.

**Comment by mvrozanti** [comment]
# MPD Visualizer :notes: 


https://github.com/user-attachments/assets/23ac321b-fd5c-4d64-a787-b65e1ac1df23


### mpd.lua
https://gist.github.com/mvrozanti/5e01ea8eff203c11d8d2b097adeb1767



---

### Config
```yaml
- effect: mpd
  group: grid
  colors: [$color1, $color2, $color3, $color4, $color5, $color6, $color7, $color8, $color9, $color10, $color11, $color12, $color13]
```

Possibly my favorite. Reads from mpd fifo file and displays amplitudes. Had to fork keyleds and [change Environment.cxx](https://github.com/mvrozanti/keyleds/commit/6eec769eb1c6d0d98c7f83e32744c48ab2b38c15) to get this to happen because lua can't read a fifo in a non-blocking manner, and it would hang the application. Still very much tweakable
